# Generated by Django 3.2.6 on 2022-07-19 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('notifications', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('general_classification_only', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('home_team', django_countries.fields.CountryField(max_length=2)),
                ('away_team', django_countries.fields.CountryField(max_length=2)),
                ('round', models.CharField(choices=[('1', 'one'), ('2', 'two'), ('3', 'three'), ('CP', 'Faza Pucharowa'), ('All', 'All')], default='1', max_length=3)),
                ('home_goals', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('away_goals', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('match_date', models.DateTimeField(blank=True, null=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('expected_home_goals', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('expected_away_goals', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True)),
                ('match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tournament.match')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
