# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 07:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_home_goals', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('expected_away_goals', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', django_countries.fields.CountryField(max_length=2)),
                ('away_team', django_countries.fields.CountryField(max_length=2)),
                ('round', models.CharField(choices=[('1', 'one'), ('2', 'two'), ('3', 'three'), ('4', 'four'), ('5', 'five'), ('6', 'six'), ('QF', 'Quarterfinal'), ('SF', 'Semifinal'), ('F', 'Final')], default='1', max_length=2)),
                ('home_goals', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('away_goals', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('match_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Tournament'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Match'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
